name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
      - uses: renovatebot/github-action@v44.2.4
        with:
          configurationFile: renovate.json
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
